version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:7000
        --access-logfile -
        --reload
        "hms.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/hms'
    ports:
      - '7000:7000'
  

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server --requirepass devpassword
    volumes:
      - 'redis:/var/lib/redis/data'
    ports:
      - '6370:6370'


  celery:
    build: .
    command: celery -A hms.blueprints.contact.tasks worker
    env_file:
      - '.env'
    volumes:
      - '.:/hms'

volumes:
  redis: